{% set version = "0.8.0" %}
{% set name = "bluesky-kafka" %}
{% set sha256 = "218e6d863f66e0f1e3cc871bc51d95018e6491389742ea1a317fd4b3125dfea5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bluesky
    - suitcase-mongo
    - msgpack-python
    - msgpack-numpy
    - python-confluent-kafka

test:
  imports:
    - bluesky_kafka

about:
  home: https://github.com/bluesky/bluesky-kafka
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The bluesky-kafka module
  dev_url: https://github.com/bluesky/bluesky-kafka

extra:
  recipe-maintainers:
    - mrakitin
    - kbeeperez
    - conda-forge/event-model
